#!/usr/bin/env python3
"""Generate a pytest test skeleton from an STDD acceptance-cases.yaml file.

Reads the given YAML file and produces one pytest test function per
acceptance case.  Error cases (those whose ``then`` section contains
``error: true``) get a ``pytest.raises`` skeleton; all other cases get
simple assertion placeholders.

Usage:
    python tools/yaml_to_pytests.py examples/order-cancellation/acceptance-cases.yaml
    python tools/yaml_to_pytests.py acceptance-cases.yaml --output tests/test_generated.py
    python tools/yaml_to_pytests.py acceptance-cases.yaml --module myapp.orders --function cancel_order
    python tools/yaml_to_pytests.py acceptance-cases.yaml --language go

Exit codes:
    0  Generation succeeded
    1  Input file not found or invalid YAML
"""

import argparse
import pathlib
import re
import sys
import textwrap
import yaml


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def slugify(name: str) -> str:
    """Turn a human-readable case name into a valid Python identifier.

    >>> slugify("cancel confirmed order -- refund triggered")
    'cancel_confirmed_order_refund_triggered'
    """
    slug = name.lower()
    slug = re.sub(r"[^a-z0-9]+", "_", slug)
    slug = slug.strip("_")
    return slug


def _format_dict_as_comments(data: dict, prefix: str = "#") -> list[str]:
    """Return a list of comment lines representing key-value pairs."""
    lines = []
    for key, value in data.items():
        lines.append(f"{prefix}   {key}: {value!r}")
    return lines


# ---------------------------------------------------------------------------
# Code generation
# ---------------------------------------------------------------------------

def generate_test_function(case: dict, target_function: str | None = None) -> str:
    """Return the source code for a single pytest test function."""
    name = case["name"]
    spec_id = case.get("spec_id", "UNKNOWN")
    given = case.get("given", {})
    when = case.get("when", {})
    then = case.get("then", {})

    func_name = f"test_{slugify(name)}"

    is_error_case = then.get("error") is True

    # Build argument string from given/when if a target function is specified
    call_stub = f"{target_function}(...)" if target_function else "call_action(...)"
    call_args = ", ".join(f"{k}={v!r}" for k, v in {**given, **when}.items())
    call_with_args = f"{target_function}({call_args})" if target_function else None

    lines: list[str] = []
    lines.append(f"def {func_name}():")
    lines.append(f'    """Acceptance case for {spec_id}: {name}."""')

    # Given
    lines.append("    # --- Given ---")
    for comment in _format_dict_as_comments(given, prefix="    #"):
        lines.append(comment)

    # When
    lines.append("    # --- When ---")
    for comment in _format_dict_as_comments(when, prefix="    #"):
        lines.append(comment)

    # Then
    lines.append("    # --- Then (expected) ---")
    for comment in _format_dict_as_comments(then, prefix="    #"):
        lines.append(comment)

    lines.append("")

    if is_error_case:
        error_code = then.get("error_code", "ExpectedError")
        if target_function:
            lines.append(f"    # TODO: verify exception type and code")
            lines.append(f"    with pytest.raises(Exception) as exc_info:")
            lines.append(f"        {call_with_args or call_stub}")
            lines.append(f"    # assert exc_info.value.code == {error_code!r}")
        else:
            lines.append(f"    # TODO: implement -- expect error with code {error_code!r}")
            lines.append(f"    # with pytest.raises(SomeException) as exc_info:")
            lines.append(f"    #     {call_stub}")
            lines.append(f"    # assert exc_info.value.code == {error_code!r}")
        lines.append("    raise NotImplementedError")
    else:
        if call_with_args:
            lines.append(f"    result = {call_with_args}")
        else:
            lines.append(f"    # TODO: implement")
            lines.append(f"    # result = {call_stub}")
        for key, value in then.items():
            prefix = "    # " if not call_with_args else "    "
            lines.append(f"{prefix}assert result.{key} == {value!r}")
        if not call_with_args:
            lines.append("    raise NotImplementedError")

    return "\n".join(lines)


def generate_module(
    cases: list[dict],
    target_module: str | None = None,
    target_function: str | None = None,
) -> str:
    """Return a complete Python test module as a string."""
    header_lines = [
        '"""Auto-generated pytest skeletons from acceptance-cases.yaml.',
        "",
        "Each test corresponds to one acceptance case.  Fill in the",
        "implementation to connect these skeletons to your production code.",
        "",
        "Generated by: tools/yaml_to_pytests.py",
        '"""',
        "",
        "import pytest",
    ]

    if target_module and target_function:
        header_lines.append(f"from {target_module} import {target_function}")
    elif target_module:
        header_lines.append(f"import {target_module}")

    header = "\n".join(header_lines) + "\n"

    body_parts = [header]
    for case in cases:
        body_parts.append("")
        body_parts.append(generate_test_function(case, target_function))

    return "\n".join(body_parts) + "\n"


# ---------------------------------------------------------------------------
# Go code generation
# ---------------------------------------------------------------------------

def generate_go_test_function(case: dict) -> str:
    """Return a single Go sub-test case for a table-driven test."""
    name = case["name"]
    spec_id = case.get("spec_id", "UNKNOWN")
    given = case.get("given", {})
    when = case.get("when", {})
    then = case.get("then", {})
    is_error_case = then.get("error") is True

    lines = [f'        {{']
    lines.append(f'            name:    "{spec_id}: {name}",')

    for key, value in {**given, **when}.items():
        lines.append(f"            // {key}: {value!r}")

    if is_error_case:
        lines.append(f"            wantErr: true,")
    else:
        for key, value in then.items():
            lines.append(f"            // want {key}: {value!r}")

    lines.append(f"        }},")
    return "\n".join(lines)


def generate_go_module(cases: list[dict]) -> str:
    """Return a Go table-driven test skeleton."""
    lines = [
        '// Auto-generated Go test skeletons from acceptance-cases.yaml.',
        "// Each sub-test corresponds to one acceptance case.",
        "// Generated by: tools/yaml_to_pytests.py --language go",
        "",
        'package TODO_test',
        "",
        'import (',
        '\t"testing"',
        "",
        '\t"github.com/stretchr/testify/assert"',
        ")",
        "",
        "func TestAcceptanceCases(t *testing.T) {",
        "\ttests := []struct {",
        '\t\tname    string',
        "\t\t// TODO: add input and expected output fields",
        '\t\twantErr bool',
        "\t}{",
    ]

    for case in cases:
        lines.append(generate_go_test_function(case))

    lines.extend([
        "\t}",
        "",
        "\tfor _, tt := range tests {",
        '\t\tt.Run(tt.name, func(t *testing.T) {',
        "\t\t\t// TODO: implement - call target function with inputs",
        "\t\t\t// result, err := CallFunction(...)",
        "\t\t\tif tt.wantErr {",
        '\t\t\t\tassert.Error(t, err)',
        "\t\t\t\treturn",
        "\t\t\t}",
        '\t\t\tassert.NoError(t, err)',
        "\t\t\t// assert.Equal(t, tt.want, result)",
        "\t\t})",
        "\t}",
        "}",
        "",
    ])

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# YAML loading
# ---------------------------------------------------------------------------

def load_cases(filepath: pathlib.Path) -> list[dict]:
    """Load acceptance cases from a YAML file.

    Supports both top-level keys ``acceptance_cases`` and
    ``acceptance-cases`` (the order-cancellation example uses an
    underscore, the template uses an underscore too, but we accept
    either for robustness).
    """
    text = filepath.read_text()
    data = yaml.safe_load(text)

    if not isinstance(data, dict):
        print(f"Error: expected a YAML mapping, got {type(data).__name__}", file=sys.stderr)
        sys.exit(1)

    # Accept both naming conventions
    cases = data.get("acceptance_cases") or data.get("acceptance-cases")
    if cases is None:
        print(
            "Error: YAML file must contain an 'acceptance_cases' or "
            "'acceptance-cases' key at the top level.",
            file=sys.stderr,
        )
        sys.exit(1)

    return cases


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate pytest test skeletons from an STDD acceptance-cases.yaml file.",
    )
    parser.add_argument(
        "yaml_file",
        help="Path to the acceptance-cases.yaml file",
    )
    parser.add_argument(
        "--output", "-o",
        default=None,
        help="Write generated code to FILE instead of stdout",
    )
    parser.add_argument(
        "--module", "-m",
        default=None,
        help="Module to import from (e.g., 'myapp.orders'). Adds an import statement.",
    )
    parser.add_argument(
        "--function", "-f",
        default=None,
        help="Target function name (e.g., 'cancel_order'). Generates call stubs with arguments.",
    )
    parser.add_argument(
        "--language", "-l",
        default="python",
        choices=["python", "go"],
        help="Target language (default: python).",
    )
    args = parser.parse_args()

    yaml_path = pathlib.Path(args.yaml_file)
    if not yaml_path.exists():
        print(f"Error: file not found: {yaml_path}", file=sys.stderr)
        sys.exit(1)

    cases = load_cases(yaml_path)

    if args.language == "go":
        output = generate_go_module(cases)
    else:
        output = generate_module(cases, args.module, args.function)

    if args.output:
        out_path = pathlib.Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(output)
        print(f"Wrote {len(cases)} test(s) to {out_path}", file=sys.stderr)
    else:
        sys.stdout.write(output)


if __name__ == "__main__":
    main()
