#!/usr/bin/env python3
"""Generate a pytest test skeleton from an STDD acceptance-cases.yaml file.

Reads the given YAML file and produces one pytest test function per
acceptance case.  Error cases (those whose ``then`` section contains
``error: true``) get a ``pytest.raises`` skeleton; all other cases get
simple assertion placeholders.

Usage:
    python tools/yaml_to_pytests.py examples/order-cancellation/acceptance-cases.yaml
    python tools/yaml_to_pytests.py examples/order-cancellation/acceptance-cases.yaml --output tests/test_generated.py

Exit codes:
    0  Generation succeeded
    1  Input file not found or invalid YAML
"""

import argparse
import pathlib
import re
import sys
import textwrap
import yaml


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def slugify(name: str) -> str:
    """Turn a human-readable case name into a valid Python identifier.

    >>> slugify("cancel confirmed order -- refund triggered")
    'cancel_confirmed_order_refund_triggered'
    """
    slug = name.lower()
    slug = re.sub(r"[^a-z0-9]+", "_", slug)
    slug = slug.strip("_")
    return slug


def _format_dict_as_comments(data: dict, prefix: str = "#") -> list[str]:
    """Return a list of comment lines representing key-value pairs."""
    lines = []
    for key, value in data.items():
        lines.append(f"{prefix}   {key}: {value!r}")
    return lines


# ---------------------------------------------------------------------------
# Code generation
# ---------------------------------------------------------------------------

def generate_test_function(case: dict) -> str:
    """Return the source code for a single pytest test function."""
    name = case["name"]
    spec_id = case.get("spec_id", "UNKNOWN")
    given = case.get("given", {})
    when = case.get("when", {})
    then = case.get("then", {})

    func_name = f"test_{slugify(name)}"

    is_error_case = then.get("error") is True

    lines: list[str] = []
    lines.append(f"def {func_name}():")
    lines.append(f'    """Acceptance case for {spec_id}: {name}."""')

    # Given
    lines.append("    # --- Given ---")
    for comment in _format_dict_as_comments(given, prefix="    #"):
        lines.append(comment)

    # When
    lines.append("    # --- When ---")
    for comment in _format_dict_as_comments(when, prefix="    #"):
        lines.append(comment)

    # Then
    lines.append("    # --- Then (expected) ---")
    for comment in _format_dict_as_comments(then, prefix="    #"):
        lines.append(comment)

    lines.append("")

    if is_error_case:
        error_code = then.get("error_code", "ExpectedError")
        lines.append(f"    # TODO: implement -- expect error with code {error_code!r}")
        lines.append(f"    # with pytest.raises(SomeException) as exc_info:")
        lines.append(f"    #     call_action(...)")
        lines.append(f"    # assert exc_info.value.code == {error_code!r}")
        lines.append("    raise NotImplementedError")
    else:
        lines.append("    # TODO: implement")
        lines.append("    # result = call_action(...)")
        for key, value in then.items():
            lines.append(f"    # assert result.{key} == {value!r}")
        lines.append("    raise NotImplementedError")

    return "\n".join(lines)


def generate_module(cases: list[dict]) -> str:
    """Return a complete Python test module as a string."""
    header = textwrap.dedent("""\
        \"\"\"Auto-generated pytest skeletons from acceptance-cases.yaml.

        Each test corresponds to one acceptance case.  Fill in the
        implementation to connect these skeletons to your production code.

        Generated by: tools/yaml_to_pytests.py
        \"\"\"

        import pytest
    """)

    body_parts = [header]
    for case in cases:
        body_parts.append("")
        body_parts.append(generate_test_function(case))

    return "\n".join(body_parts) + "\n"


# ---------------------------------------------------------------------------
# YAML loading
# ---------------------------------------------------------------------------

def load_cases(filepath: pathlib.Path) -> list[dict]:
    """Load acceptance cases from a YAML file.

    Supports both top-level keys ``acceptance_cases`` and
    ``acceptance-cases`` (the order-cancellation example uses an
    underscore, the template uses an underscore too, but we accept
    either for robustness).
    """
    text = filepath.read_text()
    data = yaml.safe_load(text)

    if not isinstance(data, dict):
        print(f"Error: expected a YAML mapping, got {type(data).__name__}", file=sys.stderr)
        sys.exit(1)

    # Accept both naming conventions
    cases = data.get("acceptance_cases") or data.get("acceptance-cases")
    if cases is None:
        print(
            "Error: YAML file must contain an 'acceptance_cases' or "
            "'acceptance-cases' key at the top level.",
            file=sys.stderr,
        )
        sys.exit(1)

    return cases


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate pytest test skeletons from an STDD acceptance-cases.yaml file.",
    )
    parser.add_argument(
        "yaml_file",
        help="Path to the acceptance-cases.yaml file",
    )
    parser.add_argument(
        "--output", "-o",
        default=None,
        help="Write generated code to FILE instead of stdout",
    )
    parser.add_argument(
        "--language", "-l",
        default="python",
        choices=["python"],
        help="Target language (default: python). Go support could be added in a future version.",
    )
    args = parser.parse_args()

    yaml_path = pathlib.Path(args.yaml_file)
    if not yaml_path.exists():
        print(f"Error: file not found: {yaml_path}", file=sys.stderr)
        sys.exit(1)

    cases = load_cases(yaml_path)
    output = generate_module(cases)

    if args.output:
        out_path = pathlib.Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(output)
        print(f"Wrote {len(cases)} test(s) to {out_path}", file=sys.stderr)
    else:
        sys.stdout.write(output)


if __name__ == "__main__":
    main()
